services:
  - type: web
    name: sistema-upload-excel-simples
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python3 sistema_simples.py
    healthCheckPath: /health